name: ai_english_tutor
description: A new Flutter project for AI English Tutor.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18+3
  google_fonts: ^6.1.0
  provider: ^6.1.1
  uuid: ^4.3.3
  intl: ^0.19.0
  animate_do: ^3.3.2
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  web_socket_channel: ^2.4.0
  record: ^6.1.2
  audioplayers: ^6.1.0
  just_audio: ^0.9.42
  permission_handler: ^11.3.0
  sound_stream: ^0.4.2
  image_picker: ^1.2.1
  audio_session: ^0.1.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
